spring:
  application:
    name: ai-agent
  datasource:
    url: jdbc:postgresql://???????/ai_agent
    username:
    password:
  ai:
    dashscope:
      api-key: ${api-key}
    chat:
      options:
        model: qwq-plus
    mcp:
      client:
        request-timeout: 30s
        stdio:
          servers-configuration: classpath:mcp-servers.json
#    vectorstore:
#      pgvector:
#        index-type: HNSW
##        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000
#  ai:
#    openai:
#      api-key: sk-clrabotwvlprccqebhlktqivaacslevtklosifdvxbalikdq
#      base-url: https://api.siliconflow.cn/v1/chat/completions
#      chat:
#        options:
#          model: deepseek-r1

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hp.aiagent.controller.HealthController

knife4j:
  enable: true
  setting:
    language: zh_cn
search-api:
  api-key: ${search-api.api-key}
